In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/ICT202 Machine Learning/iris.csv")

##Exploreing the dataset

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   sepal length   150 non-null    float64
 1   sepal width    150 non-null    float64
 2    petal length  150 non-null    float64
 3    petal width   150 non-null    float64
 4   class          150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [ ]:
df.describe()

sepal length  sepal width   petal length   petal width
count    150.000000   150.000000     150.000000    150.000000
mean       5.843333     3.054000       3.758667      1.198667
std        0.828066     0.433594       1.764420      0.763161
min        4.300000     2.000000       1.000000      0.100000
25%        5.100000     2.800000       1.600000      0.300000
50%        5.800000     3.000000       4.350000      1.300000
75%        6.400000     3.300000       5.100000      1.800000
max        7.900000     4.400000       6.900000      2.500000

In [ ]:
df.head()

sepal length  sepal width   petal length   petal width        class
0           5.1          3.5            1.4           0.2  Iris-setosa
1           4.9          3.0            1.4           0.2  Iris-setosa
2           4.7          3.2            1.3           0.2  Iris-setosa
3           4.6          3.1            1.5           0.2  Iris-setosa
4           5.0          3.6            1.4           0.2  Iris-setosa

In [ ]:
df.dtypes #type of each of the attributes

sepal length     float64
sepal width      float64
 petal length    float64
 petal width     float64
class             object
dtype: object

In [ ]:
df.tail()

sepal length  sepal width   petal length   petal width           class
145           6.7          3.0            5.2           2.3  Iris-virginica
146           6.3          2.5            5.0           1.9  Iris-virginica
147           6.5          3.0            5.2           2.0  Iris-virginica
148           6.2          3.4            5.4           2.3  Iris-virginica
149           5.9          3.0            5.1           1.8  Iris-virginica

In [ ]:
df['class'].value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: class, dtype: int64

In [ ]:
# Define the predictor(s) (X) and target attribute (y)

X = df.iloc[:,:-1].values # -1 can be replaced by 4
y = df.iloc[:,-1].values #-1 can also be replaced by 4

In [ ]:
from sklearn.preprocessing import LabelEncoder
LabelEncoder_y = LabelEncoder()
y = LabelEncoder_y.fit_transform(y)
# fit + transform - we are doing label encoding here

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
#Split the dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=0)

In [ ]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler();
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

## Building the model

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn = KNeighborsClassifier(n_neighbors = 5, metric = "minkowski", p = 2)

In [ ]:
# Pass for training
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [ ]:
y_pred = knn.predict(X_test)
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 2, 2, 0, 2, 1, 0, 0, 2, 2,
       0, 0, 2, 0, 0, 1, 1, 0])

In [ ]:
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0])

## Evaluate

In [ ]:
#Making a confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[11,  0,  0],
       [ 0,  9,  4],
       [ 0,  0,  6]])

In [ ]:
#Finding the accuracy
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test, y_pred)
ac

0.8666666666666667

In [ ]:
#Balanced dataset, so actually dont need to run this, but we still need to run it nonetheless

#Finding the precision
from sklearn.metrics import precision_score
pc = precision_score(y_test, y_pred, average = 'micro')
pc

0.8666666666666667

In [ ]:
#Finding the precision
from sklearn.metrics import f1_score
fc = f1_score(y_test, y_pred, average = 'micro')
fc

0.8666666666666667